# Generated by Django 5.2.4 on 2025-07-10 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_loations_event_location_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
