services:
  - type: web
    name: event-registration
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project_name.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: your_secret_key
      - key: DEBUG
        value: False
